### ISSUE TITLE
Changes to the official website

### ISSUE THREAD

**Issue by LordStephen77** [DreamBlocks/dreamblocks.github.io#1]
@azekillDIABLO @tobyplowy @tobyplowy Modify all links. I published the .jar executable in the official repository of the project (last release with corrections and code enhancements).

The official site is already visible to everyone! Github publishes it automatically. So you can safely make the changes and see them posted just as soon as your commit is approved.

Thank you all.

**Comment by azekillDIABLO** [comment]
i will get rid of the dead links and remove my repo this weekend! happy to work in collaboration with you! (ps: i also noticed a little width change on gallery, that may be the .middle class)

thx :smiley:

**Comment by LordStephen77** [comment]
@azekillDIABLO Thanks so much. When you can dedicate to the site, I like to see you commit and passionate. It improves the legibility of the text. Sharing with others is the most beautiful thing. Thank you.
