### ISSUE TITLE
text on website is very small and blends in the background

### ISSUE THREAD

**Issue by tobyplowy** [DreamBlocks/dreamblocks.github.io#4]
maybe make the blue text a littlebit biggr and not blue but black
![image](https://user-images.githubusercontent.com/16853304/27448899-cd226aca-5786-11e7-93fc-14b37bb372b9.png)

**Comment by LordStephen77** [comment]
Create a semi-transparent dark gray panel with white text (12px text size, 14px subtitles, page title 18px). I think it's the best solution.

**Comment by LordStephen77** [comment]
I almost finished the new official site!

- HTML5 and CSS3
- Bootstrap added (the site is responsive, optimized for desktop and mobile devices)
- Clean, orderly and easy to understand code (my main.css form to simplify formatting)
- Simple and modern design

**Comment by azekillDIABLO** [comment]
thank you , this website is AWESOME!

**Comment by tobyplowy** [comment]
@LordStephen77 wow nice work with that website!
